const root=document.getElementById('loop-atlas-proposal');
const cards=[...root.querySelectorAll('[data-paper]')];
const boxes=[...root.querySelectorAll('[data-compare]')];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const valid=new Set(cards.map(c=>c.dataset.paper));
let selected=new Set(),filter='all',query='',view='explore';
const search=root.querySelector('#la-search');
function readURL(){const p=new URLSearchParams(location.search);filter=['adaptive','core','full'].includes(p.get('filter'))?p.get('filter'):'all';query=p.get('q')||'';view=['timeline','compare'].includes(p.get('view'))?p.get('view'):'explore';selected=new Set((p.get('compare')||'').split(',').filter(id=>valid.has(id)).slice(0,3));search.value=query;}
function saveURL(push=false){const p=new URLSearchParams();if(view!=='explore')p.set('view',view);if(filter!=='all')p.set('filter',filter);if(query)p.set('q',query);if(selected.size)p.set('compare',[...selected].join(','));const target=location.pathname+(p.size?'?'+p:'');history[push?'pushState':'replaceState'](null,'',target);}
function render(){const old=new Map(cards.filter(c=>!c.hidden).map(c=>[c,c.getBoundingClientRect()]));let count=0;cards.forEach(card=>{card.hidden=!((filter==='all'||card.dataset.group===filter)&&card.dataset.search.includes(query.toLowerCase()));if(!card.hidden)count++;});root.querySelector('#la-results').textContent=count+' '+(count===1?'work':'works');root.querySelector('#la-empty').hidden=count!==0;root.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));['explore','timeline','compare'].forEach(v=>root.querySelector('#la-'+v).hidden=view!==v);root.querySelectorAll('[data-view]').forEach(a=>{if(a.dataset.view===view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});boxes.forEach(b=>{b.checked=selected.has(b.dataset.compare);b.disabled=selected.size===3&&!b.checked;});root.querySelector('#la-count').textContent=String(selected.size);root.querySelectorAll('[data-comparison]').forEach(c=>c.hidden=!selected.has(c.dataset.comparison));root.querySelector('#la-comparison-help').hidden=selected.size>0;root.querySelector('#la-clear').disabled=!selected.size;root.querySelector('#la-selection').hidden=!selected.size||view==='compare';root.querySelector('#la-selected-text').textContent=selected.size+' of 3 selected';if(!reduced.matches&&view==='explore')cards.filter(c=>!c.hidden).forEach(card=>{const prev=old.get(card),now=card.getBoundingClientRect();if(prev&&(prev.x!==now.x||prev.y!==now.y))card.animate([{transform:`translate(${prev.x-now.x}px,${prev.y-now.y}px)`},{transform:'translate(0,0)'}],{duration:400,easing:'cubic-bezier(.2,.7,.2,1)'});});}
function changeView(v){view=v;saveURL(true);render();}
root.querySelectorAll('[data-view]').forEach(a=>a.addEventListener('click',e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();changeView(a.dataset.view);}));
root.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;saveURL();render();}));
search.addEventListener('input',()=>{query=search.value;saveURL();render();});
boxes.forEach(b=>b.addEventListener('change',()=>{if(b.checked&&selected.size<3)selected.add(b.dataset.compare);else selected.delete(b.dataset.compare);saveURL();render();}));
root.querySelector('#la-open-compare').addEventListener('click',e=>{e.preventDefault();changeView('compare');root.querySelector('#la-compare').scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'start'});});
root.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{selected.delete(b.dataset.remove);saveURL();render();}));
root.querySelector('#la-clear').addEventListener('click',()=>{selected.clear();saveURL();render();});
window.addEventListener('popstate',()=>{readURL();render();});
cards.forEach(el=>{el.onpointermove=e=>{if(e.pointerType==='touch'||reduced.matches)return;const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;el.style.setProperty('--la-rx',((.5-y)*4)+'deg');el.style.setProperty('--la-ry',((x-.5)*4)+'deg');el.style.setProperty('--la-mx',x*100+'%');el.style.setProperty('--la-my',y*100+'%');};el.onpointerleave=()=>{el.style.setProperty('--la-rx','0deg');el.style.setProperty('--la-ry','0deg');};});
readURL();render();
